services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obsidian-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - SECRET_KEY=${SECRET_KEY:-please-change-this-secret-key-in-production}
      - DATABASE_URL=sqlite:///data/app.db
      - VAULTS_ROOT=/data/vaults
      - INDEXES_ROOT=/data/indexes
      - CORS_ORIGINS=http://0.0.0.0:5173,http://0.0.0.0:80,http://0.0.0.0,http://obsidian-frontend,http://frontend
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obsidian-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  default:
    name: obsidian-network
